dist: trusty
sudo: false
language: php

install:
- phpenv config-rm xdebug.ini || return 0

jobs:
  include:
  - stage: deploy
    php: 7.0
    before_script: skip
    script:
    - if [[ "$TRAVIS_TAG" ]]; then
        sed -i 's/cart-integration-magento2-//g' composer.json;
        zip shopgate-m2-${TRAVIS_TAG}.zip composer.json;
      fi
    deploy:
      provider: releases
      api_key:
        secure: "Jfa/CeO/yp2rsUpGiGc0aBwrPZNEcx9l227wTIqUCHwlIA4h65PBURNsf7Lo1gyWCpQr9B5ApsW+V+qEQaFb/i71rq3EY7Trk9QqzeZlGxg/kkAncg1xHfrK/O1SQsLcO5kaoxcc+0p0T/fFEE0DrEngT09SdO8S0HUvjOm9+2rq3ja16d2dRVovMoPUJYsVTgHIHZkALwFoOltyliDzZImSiQrhJiYP3ql2uBsdUH4GS+0mF85k7kE2avR3o3GYCyJE/BDuW2328RAOHAzjVirTDBDV3gFadHbRWV2aNbf4gygkFO298rTUrt7KQssv0H7eeipqvd5qOeQKk2/Kjc3XNHfIhWYvsH5hdZYs03iRekyfsTxzfdYHnySLHhgDdho1MHqpAvee7+034GvIRLl4rOUb03n01cH/lhJaVgHJDDxhIXwIUuyh3ZC8BuERvKVWrSIAWpKoau5NN6A4z951Grdkb0FiaTvSfB3nU6PLuZgrVutIMK86TbEoB81FaJH5eFOaWDuPGk7/0/XIfAQPW3Fkf6vtP9wBIUGlgHDBXGvwY6KiM3J8x46F7MHEjuTyzEsywQVAekzrJGYHrEnrtFERIQ1zGzLwyphphm68k1HwyrhaG4Z1wmOXWyyCFZSWR3sFshmvFWmiVgj2sKAjSkKQFEpIWtlaWi6qjiA="
      file: shopgate-m2-${TRAVIS_TAG}.zip
      skip_cleanup: true
      on:
        tags: true

notifications:
  slack:
    rooms:
      - secure: "JOsMtFPP+M92BIakAJlSXGyH7QyS2bn7GMH/Nrtn0l2iBCm0HhYDjsPigEkg5g/aijVv4n61+/bhQJDtE2mVyZp1YFWgRyrvatRn3cPLSprx1T2cYmU5ojWsAV6SC6R8+DEn1MnQ57t9xBs6eVvDrf87lct0kqRZMkXb6Lf0gDBk3pyLWCBwUCmfg5Sq55jcB9je2UYkt9lNImT4xTpqRw0G2e+Nbk7LLhCO4cVdUzowlR1fS+scKWhSCuY5C9//jFpg5Q6868j7cIylrfcZNggpcpZeMMLa7i7b8i7BcpYp4ZlI81BcDBf/K87dtNT6o4sBj18wYj6VcgZi0jFHG9R2XEUhkx18bBgGM51zHPzPi9dmlgeGXWnqxul9vMceLN1IZitCLH+uV9pmVHMjFq7JZckYhwsHCEl3lGEa1kugWLYFbgFy6VApcvLg0X77gL1uk3X3kzSVPnJypSnpB8WjkI6FnU9SRJ2tSWCgDadobQMyM8NfTcTjhq6seX/PZXHDu386pJDHIdXM7pHXGi2B+vPVh8NDHhye01Z2tI4EQZiuleHXvc/0lFR6N6b9rT4R5fP22jsVL8m++2nesMbBh7vt89Y4c8N+ijIEevHFSxg4a1zxa61dkT7y3yksrLkfBwZYlV4HBKbXNWTxJmk7wVVko66J+2JIRB+4noI="
    on_success: change
    on_failure: always
